# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_custom',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_custom',
        ),
    ]
