# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('city_title', models.CharField(max_length=200)),
                ('city_desc', models.CharField(max_length=500)),
                ('city_img', models.ImageField(default='default.jpeg', upload_to='')),
                ('city_rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_title', models.CharField(max_length=200)),
                ('country_desc', models.CharField(max_length=500)),
                ('country_img', models.ImageField(default='default.jpeg', upload_to='')),
                ('country_rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_site.Country'),
        ),
    ]
