# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_description', models.CharField(max_length=250)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_site.City')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('exp_title', models.CharField(max_length=200)),
                ('exp_description', models.CharField(max_length=250)),
                ('exp_img', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_site.City')),
            ],
        ),
        migrations.CreateModel(
            name='Sights',
            fields=[
                ('sight_id', models.AutoField(primary_key=True, serialize=False)),
                ('sight_name', models.CharField(max_length=200)),
                ('sight_img', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_site.City')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_site.Experience'),
        ),
    ]
