# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_site', '0002_auto_20190215_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count', to='home_site.Country'),
        ),
    ]
