# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_site', '0002_user_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
