# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_site', '0003_auto_20190220_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_custom',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_custom',
        ),
    ]
